apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-api
  namespace: microservice-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard-api
  template:
    metadata:
      labels:
        app: dashboard-api
    spec:
      containers:
      - name: api
        image: huhnbp/microservice-dashboard:latest
        ports:
        - containerPort: 8080
