apiVersion: v1
kind: Service
metadata:
  name: dashboard-api
  namespace: microservice-dashboard
spec:
  selector:
    app: dashboard-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
